server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/halozalo
    username: halozalo
    password: halozalo
    hikari:
      connection-init-sql: SET search_path TO identity
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
