server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity
    username: halozalo
    password: halozalo
    hikari:
      connection-init-sql: USE identity
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
